### ISSUE TITLE
Refactor to support multiple modules.

### ISSUE THREAD

**Issue by talktocory** [open-campaign-logger/compendium-generator#16]
While the current solution works well for 5e it's structure limits the ability to add new modules easily.  Going to take a quick step back and refactor slightly.

## ToDo
* [x] Add Compendium Interface
* [x] Add Monster Interface
* [x] Update app to load appropriate ICompendiumService via reflection.
