### ISSUE TITLE
Prepare for Initial Release

### ISSUE THREAD

**Issue by talktocory** [open-campaign-logger/compendium-generator#40]
A number of house keeping tasks need to be performed to get the project ready for its initial release.

### ToDo
* [ ] Add work management best practices to readme
* [ ] Add contributor best practices to readme
* [ ] Configure build, test and deploy pipeline
